# docker-compose.yml

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-builder
        ports:
            - 3000:3000
            - 9001:9001
            - 5000:5000
        volumes:
            - ./:/home/node/app:rw,cached
        user: node
        working_dir: /home/node/app
        tty: true